global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: '/(.*)'
        replacement: '${1}'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: '/(.*)'
        replacement: '${1}'

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:9187']
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: '/(.*)'
        replacement: '${1}'

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: '/(.*)'
        replacement: '${1}'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - "rules/*.rules"

# External URL for Prometheus
external_url: "https://metrics.jusapp.com/"

# Remote write configuration
remote_write:
  - url: "http://remote-prometheus:9090/api/v1/write"
    basic_auth:
      username: 'prometheus'
      password: 'your-secure-password'

# Remote read configuration
remote_read:
  - url: "http://remote-prometheus:9090/api/v1/read"
    basic_auth:
      username: 'prometheus'
      password: 'your-secure-password'