"""add ago and pms columns to trucks table

Revision ID: 5794a4c1a5b2
Revises: 
Create Date: 2025-05-09 02:49:57.514516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5794a4c1a5b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trucks', sa.Column('ago', sa.Float(), nullable=False))
    op.add_column('trucks', sa.Column('pms', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucks', 'pms')
    op.drop_column('trucks', 'ago')
    # ### end Alembic commands ###
